name: Update Skill Count Badge

on:
  push:
    branches: [main]
    paths:
      - 'README.md'
  workflow_dispatch:

jobs:
  count-skills:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Count Skills
        id: count
        run: |
          # Count verified skills (those with ✅)
          VERIFIED_COUNT=$(grep -c "| \*\*Verified:\*\* ✅" README.md || echo "0")
          # Count all skills (those with Source: or Status:)
          TOTAL_COUNT=$(grep -cE "(Source:|Status:)" README.md || echo "0")
          echo "verified=$VERIFIED_COUNT" >> $GITHUB_OUTPUT
          echo "total=$TOTAL_COUNT" >> $GITHUB_OUTPUT
          echo "Found $VERIFIED_COUNT verified skills out of $TOTAL_COUNT total"

      - name: Update README Badge
        run: |
          TOTAL=${{ steps.count.outputs.total }}
          sed -i "s/skills-[0-9]*+-brightgreen/skills-${TOTAL}+-brightgreen/" README.md

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update skill count badge to ${{ steps.count.outputs.total }}+"
          file_pattern: README.md
